import type { ImageSourcePropType } from "react-native"

import type { Book } from "@/services/books"

// This shelf is intentionally local so the public home-page preview can render
// without waiting for book-search requests.
export const HOME_PREVIEW_COVERS: Record<string, ImageSourcePropType> = {
  "preview-kurk-mantolu-madonna": require("../assets/images/book-covers/kurk-mantolu-madonna.jpg"),
  "preview-ince-memed": require("../assets/images/book-covers/ince-memed.jpg"),
  "preview-saatleri-ayarlama-enstitusu": require("../assets/images/book-covers/saatleri-ayarlama-enstitusu.jpg"),
  "preview-tutunamayanlar": require("../assets/images/book-covers/tutunamayanlar.jpg"),
  "preview-otomatik-portakal": require("../assets/images/book-covers/otomatik-portakal.jpg"),
  "preview-left-hand-of-darkness": require("../assets/images/book-covers/the-left-hand-of-darkness.jpg"),
  "preview-pride-and-prejudice": require("../assets/images/book-covers/pride-and-prejudice.jpg"),
  "preview-the-little-prince": require("../assets/images/book-covers/the-little-prince.jpg"),
  "preview-nineteen-eighty-four": require("../assets/images/book-covers/nineteen-eighty-four.jpg"),
}

export const HOME_PREVIEW_BOOKS: Book[] = [
  {
    id: "preview-kurk-mantolu-madonna",
    owner_id: "preview-reader-1",
    owner_name: "Ayşe",
    community_id: "preview-community-kadikoy",
    community_name: "Kadıköy Kitap Kulübü",
    title: "Kürk Mantolu Madonna",
    author: "Sabahattin Ali",
    description: null,
    cover_url: null,
    isbn: null,
    status: "available",
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "preview-ince-memed",
    owner_id: "preview-reader-2",
    owner_name: "Deniz",
    community_id: "preview-community-besiktas",
    community_name: "Beşiktaş Okurları",
    title: "İnce Memed",
    author: "Yaşar Kemal",
    description: null,
    cover_url: null,
    isbn: null,
    status: "available",
    created_at: "2026-01-02T00:00:00Z",
  },
  {
    id: "preview-saatleri-ayarlama-enstitusu",
    owner_id: "preview-reader-3",
    owner_name: "Ece",
    community_id: "preview-community-cankaya",
    community_name: "Çankaya Paylaşım Rafı",
    title: "Saatleri Ayarlama Enstitüsü",
    author: "Ahmet Hamdi Tanpınar",
    description: null,
    cover_url: null,
    isbn: null,
    status: "available",
    created_at: "2026-01-03T00:00:00Z",
  },
  {
    id: "preview-tutunamayanlar",
    owner_id: "preview-reader-4",
    owner_name: "Mert",
    community_id: "preview-community-kadikoy",
    community_name: "Kadıköy Kitap Kulübü",
    title: "Tutunamayanlar",
    author: "Oğuz Atay",
    description: null,
    cover_url: null,
    isbn: null,
    status: "available",
    created_at: "2026-01-04T00:00:00Z",
  },
  {
    id: "preview-otomatik-portakal",
    owner_id: "preview-reader-5",
    owner_name: "Selin",
    community_id: "preview-community-moda",
    community_name: "Moda Sci-Fi Readers",
    title: "Otomatik Portakal",
    author: "Anthony Burgess",
    description: null,
    cover_url: null,
    isbn: null,
    status: "available",
    created_at: "2026-01-05T00:00:00Z",
  },
  {
    id: "preview-left-hand-of-darkness",
    owner_id: "preview-reader-6",
    owner_name: "Maya",
    community_id: "preview-community-moda",
    community_name: "Moda Sci-Fi Readers",
    title: "The Left Hand of Darkness",
    author: "Ursula K. Le Guin",
    description: null,
    cover_url: null,
    isbn: null,
    status: "available",
    created_at: "2026-01-06T00:00:00Z",
  },
  {
    id: "preview-pride-and-prejudice",
    owner_id: "preview-reader-7",
    owner_name: "Elif",
    community_id: "preview-community-cankaya",
    community_name: "Çankaya Paylaşım Rafı",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    description: null,
    cover_url: null,
    isbn: null,
    status: "available",
    created_at: "2026-01-07T00:00:00Z",
  },
  {
    id: "preview-the-little-prince",
    owner_id: "preview-reader-8",
    owner_name: "Can",
    community_id: "preview-community-besiktas",
    community_name: "Beşiktaş Okurları",
    title: "The Little Prince",
    author: "Antoine de Saint-Exupéry",
    description: null,
    cover_url: null,
    isbn: null,
    status: "available",
    created_at: "2026-01-08T00:00:00Z",
  },
  {
    id: "preview-nineteen-eighty-four",
    owner_id: "preview-reader-9",
    owner_name: "Ada",
    community_id: "preview-community-moda",
    community_name: "Moda Sci-Fi Readers",
    title: "Nineteen Eighty-Four",
    author: "George Orwell",
    description: null,
    cover_url: null,
    isbn: null,
    status: "available",
    created_at: "2026-01-09T00:00:00Z",
  },
]
